### ISSUE TITLE
构建 grammer db 的原始格式？

### ISSUE THREAD

**Issue by faywong** [lotem/librime-octagram#3]
我从 build_grammer.cc 的代码反推，应该是：

```bash
一行字符串
一行该字符串出现的频率
```

查询的时候，是用前缀字典树检索，获得这个近似的 n-gram 概率。

请问，是这样的吗？

**Comment by lotem** [comment]
是的。

統計結果是分詞的，餵給 build_grammer 之前用腳本處理過。
Rime 的詞典由各個輸入方案自行定義，沒有統一的分詞標準，無法以詞爲單位查詢。
於是採取了按照字符串查詢語言模型的折衷方案。

**Comment by lotem** [comment]
libpinyin 是後起的，我不知道技術上有什麼創新？如果只是重複實現 SunPinyin 做過的，那就意義不大。
Rime 立項之前我着重考察了 SunPinyin，因爲數據結構與拼音方案耦合的問題而無法在其基礎上開發。
